version: "3.8"

services:
    # Django web application
    web:
        build: .
        restart: always
        volumes:
            - ./QAU_API:/app/QAU_API
        ports:
            - "8000:8000"
        depends_on:
            - db
        environment:
            - DATABASE_URL=${DATABASE_URL}
            - SECRET_KEY=${SECRET_KEY}
            - DEBUG=${DEBUG}
            - ALLOWED_HOSTS={$ALLOWED_HOSTS}
            - DJANGO_SUPERUSER_EMAIL=${DJANGO_SUPERUSER_EMAIL}
            - DJANGO_SUPERUSER_USERNAME=${DJANGO_SUPERUSER_USERNAME}
            - DJANGO_SUPERUSER_ROLE=${DJANGO_SUPERUSER_ROLE}
            - DJANGO_SUPERUSER_PASSWORD=${DJANGO_SUPERUSER_PASSWORD}
        command: >
            sh -c "python QAU_API/manage.py migrate --noinput &&
                pip install --no-cache-dir -r QAU_API/requirements.txt &&
                python QAU_API/manage.py runserver 0.0.0.0:8000"

    # PostgreSQL database
    db:
        image: postgres:16
        restart: always
        volumes:
            - postgres_data_v1:/var/lib/postgresql/data/
        environment:
            - POSTGRES_DB=${POSTGRES_DB}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        ports:
            - "5432:5432"

volumes:
    postgres_data_v1:
