# Generated by Django 5.2 on 2025-05-10 11:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('standards', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='shared_with',
            field=models.ManyToManyField(blank=True, related_name='shared_attachments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attachment',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_attachments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attachment',
            name='element',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='standards.element'),
        ),
        migrations.AddField(
            model_name='element',
            name='pointer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='standards.pointer'),
        ),
        migrations.AddField(
            model_name='request',
            name='made_on',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='standards.attachment'),
        ),
        migrations.AddField(
            model_name='request',
            name='receiver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='request',
            name='requester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='standard',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standards', to='standards.academicyear'),
        ),
        migrations.AddField(
            model_name='standard',
            name='assigned_to',
            field=models.ManyToManyField(blank=True, related_name='assigned_standards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pointer',
            name='standard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pointers', to='standards.standard'),
        ),
    ]
