# Generated by Django 5.2 on 2025-05-12 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='department',
            field=models.CharField(blank=True, choices=[('AI', 'Artificial Intelligence'), ('CS', 'Computer Science'), ('NT', 'Network'), ('IS', 'Information Systems')], max_length=50),
        ),
    ]
